export interface AuditTrial {    

    InternalId?: any;

    Description?: string;
    SubscriptionNo?: string;
    UserNameWhoUpdated?: number;
    Date?: any;

}

// public class AuditTrial
//     {
//         [BsonId]
//         // standard BSonId generated by MongoDb
//         public ObjectId InternalId { get; set; }

//         public string Description { get; set; }
//         public string SubscriptionNo { get; set; }
//         public string UserNameWhoUpdated { get; set; }
//         public DateTime Date { get; set; }
//     }