export interface SubscriptionType {    

    InternalId?: any;

    TypeId?: number;
    Name?: string;
    Days?: number;

    LoyaltyPoints?: number;
    CreatedDate?: any;
    ModifiedDate?: any;

}

// public class SubscriptionType
// {
//     [BsonId]
//     // standard BSonId generated by MongoDb
//     public ObjectId InternalId { get; set; }

//     public int TypeId { get; set; }
//     public string Name { get; set; }
//     public int Days { get; set; }

//     public int LoyaltyPoints { get; set; }
//     public DateTime CreatedDate { get; set; }
//     public DateTime ModifiedDate { get; set; }
// }