export interface Subscriber {    

    InternalId?: any;

    SNo?: number;
    CreatedDate?: any;
    SubscriptionNo?: string;
    CustomerName?: string;
    TypeId?: number;
    Address1?: string;
    Address2?: string;
    Address3?: string;
    City?: string;
    State?: string;
    Country?: string;
    Pin?: string;
    Email?: string;
    Mobile?: string;
    Phone?: string;
    ModifiedDate?: any;
    Comments?: string;
    DueDate?: any;
    IsInvalid?: boolean;

    CreatedByUserName?: string;
    LoyaltyUserId?: number;
    RenewedDate?: any;

}

// public class Subscriber
//     {
//         [BsonId]
//         // standard BSonId generated by MongoDb
//         public ObjectId InternalId { get; set; }

//         public int SNo { get; set; }
//         public DateTime CreatedDate { get; set; }
//         public string SubscriptionNo { get; set; }
//         public string CustomerName { get; set; }
//         public int TypeId { get; set; }
//         public string Address1 { get; set; }
//         public string Address2 { get; set; }
//         public string Address3 { get; set; }
//         public string City { get; set; }
//         public string State { get; set; }
//         public string Country { get; set; }
//         public string Pin { get; set; }
//         public string Mobile { get; set; }
//         public string Phone { get; set; }
//         public DateTime ModifiedDate { get; set; }
//         public string Comments { get; set; }
//         public DateTime? DueDate { get; set; }
//         public bool IsInvalid { get; set; }

//         public string CreatedByUserName { get; set; }
//         public int LoyaltyUserId { get; set; }
//         public DateTime? RenewedDate { get; set; }
//     }