export interface User {    

    InternalId?: any;

    UserName?: string;
    Password?: string;
    RoleId?: any;
    IsEnabled?: boolean;
    CreatedDate?: any;
    ModifiedDate?: any;

}


// public class User
// {
//     [BsonId]
//     // standard BSonId generated by MongoDb
//     public ObjectId InternalId { get; set; }

//     public string UserName { get; set; }
//     public string Password { get; set; }
//     public Role RoleId { get; set; }
//     public bool IsEnabled { get; set; }
//     public DateTime CreatedDate { get; set; }
//     public DateTime ModifiedDate { get; set; }
// }