import { Injectable } from '@angular/core';
import { Subscriber } from '../models/subscriber';
import { Observable } from 'rxjs';
import { FormControl, FormGroup, Validators } from "@angular/forms"

@Injectable({
  providedIn: 'root'
})
export class SubscriberService {

  subscribers: Observable<Subscriber[]>;

  constructor() { }

  subscribersForm = new FormGroup({
    InternalId: new FormControl(null),
    SNo: new FormControl(''),
    CreatedDate: new FormControl(''),
    SubscriptionNo: new FormControl('', Validators.required),
    CustomerName: new FormControl('', [Validators.required, Validators.maxLength(40)]),
    TypeId: new FormControl('', Validators.required),
    NewTypeId: new FormControl('', Validators.required),
    Address1: new FormControl('', [Validators.required, Validators.maxLength(20)]),
    Address2: new FormControl('', [Validators.required, Validators.maxLength(20)]),
    Address3: new FormControl(''),
    City: new FormControl('', Validators.required),
    State: new FormControl('', Validators.required),
    Country: new FormControl('', Validators.required),
    Pin: new FormControl('', Validators.required),
    Email: new FormControl('', [Validators.required, Validators.email]),
    Mobile: new FormControl('', [Validators.required, Validators.minLength(8)]),
    Phone: new FormControl(''),
    ModifiedDate: new FormControl(''),
    Comments: new FormControl(''),
    DueDate: new FormControl(''),
    NewDueDate: new FormControl(''),
    IsInvalid: new FormControl(''),
    CreatedByUserName: new FormControl(''),
    LoyaltyUserId: new FormControl('', Validators.required),
    NewLoyaltyUserId: new FormControl('', Validators.required),
    RenewedDate: new FormControl(''),
    NewRenewedDate: new FormControl('')
  })

  insertSubscriber(model) {

    console.log(model);
    // After writing the values into database
    this.subscribersForm.reset();
  }

  editSubscriber(model) {

    console.log(model);
    // After writing the values into database
    this.subscribersForm.reset();
  }

  deleteSubscriber(model) {
    console.log(model);
    this.subscribersForm.reset();
  }

  loadForm(sub) {
    console.log(sub);
    this.subscribersForm.setValue(sub);
  }

  getSubscribers() {

    let data = [
      {
        "InternalId": "5c13db65596f7040c19f4fb3",
        "SNo": 0,
        "CreatedDate": "2017-10-19",
        "SubscriptionNo": "5c13db65a6be9910609fa62d",
        "CustomerName": "Sara Parsons",
        "TypeId": 1,
        "Address1": "533 Doscher Street",
        "Address2": "Veyo",
        "Address3": "Montana, 4019",
        "City": "Chalfant",
        "State": "Utah",
        "Country": "Guam",
        "Pin": "9083A",
        "Email": "saraparsons@rameon.com",
        "Mobile": "+1 (831) 591-2960",
        "Phone": "+1 (978) 571-3839",
        "ModifiedDate": "2014-09-20",
        "Comments": "Do veniam velit laboris adipisicing deserunt non. Cillum sunt culpa ea consequat et pariatur ullamco. Ex reprehenderit nostrud magna nulla eiusmod.\r\n",
        "DueDate": "2018-03-19",
        "IsInvalid": true,
        "CreatedByUserName": "Robbie",
        "LoyaltyUserId": 186,
        "RenewedDate": "2015-01-05",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 5236,
        "NewRenewedDate": "2014-06-08",
        "NewDueDate": "2014-12-10"
      },
      {
        "InternalId": "5c13db65af5ac504b2f097b6",
        "SNo": 1,
        "CreatedDate": "2017-10-15",
        "SubscriptionNo": "5c13db655d6f691b9bef3aa1",
        "CustomerName": "Farley Gilmore",
        "TypeId": 3,
        "Address1": "711 Schenck Street",
        "Address2": "Rivereno",
        "Address3": "Iowa, 1836",
        "City": "Southmont",
        "State": "Rhode Island",
        "Country": "Arkansas",
        "Pin": "5640A",
        "Email": "farleygilmore@rameon.com",
        "Mobile": "+1 (871) 582-2011",
        "Phone": "+1 (894) 493-3844",
        "ModifiedDate": "2018-05-09",
        "Comments": "Aliqua duis ut enim deserunt aute. Culpa laborum ex magna sunt veniam laboris tempor. Laboris deserunt Lorem quis officia fugiat ullamco.\r\n",
        "DueDate": "2017-01-25",
        "IsInvalid": true,
        "CreatedByUserName": "Trina",
        "LoyaltyUserId": 9214,
        "RenewedDate": "2017-08-14",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 6060,
        "NewRenewedDate": "2014-09-20",
        "NewDueDate": "2015-03-28"
      },
      {
        "InternalId": "5c13db65faa02983e5bdc493",
        "SNo": 2,
        "CreatedDate": "2018-05-06",
        "SubscriptionNo": "5c13db651d093f39d91dd5e5",
        "CustomerName": "Mathews Nieves",
        "TypeId": 2,
        "Address1": "170 Hubbard Place",
        "Address2": "Cloverdale",
        "Address3": "Illinois, 6452",
        "City": "Orick",
        "State": "Arizona",
        "Country": "California",
        "Pin": "1218A",
        "Email": "mathewsnieves@rameon.com",
        "Mobile": "+1 (841) 498-2174",
        "Phone": "+1 (907) 410-2114",
        "ModifiedDate": "2016-02-13",
        "Comments": "Id qui commodo consequat velit duis laborum non tempor. Sint tempor elit qui occaecat id nostrud do aute. Ea excepteur commodo exercitation mollit ex culpa deserunt consectetur exercitation veniam duis eu incididunt. Ex ipsum fugiat sunt aliquip. Commodo sit elit pariatur sunt enim amet adipisicing et amet cillum dolor.\r\n",
        "DueDate": "2014-07-15",
        "IsInvalid": true,
        "CreatedByUserName": "Sandoval",
        "LoyaltyUserId": 5035,
        "RenewedDate": "2016-05-13",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 3128,
        "NewRenewedDate": "2014-04-29",
        "NewDueDate": "2015-03-01"
      },
      {
        "InternalId": "5c13db657369e4d12e08ed26",
        "SNo": 3,
        "CreatedDate": "2016-12-23",
        "SubscriptionNo": "5c13db65c4b16a7cff33c273",
        "CustomerName": "Serrano Rasmussen",
        "TypeId": 3,
        "Address1": "563 Ocean Parkway",
        "Address2": "Sussex",
        "Address3": "Ohio, 4614",
        "City": "Springhill",
        "State": "Kansas",
        "Country": "Idaho",
        "Pin": "1488A",
        "Email": "serranorasmussen@rameon.com",
        "Mobile": "+1 (891) 495-3493",
        "Phone": "+1 (899) 408-2821",
        "ModifiedDate": "2016-04-03",
        "Comments": "Eu quis sunt consequat dolor ipsum occaecat anim nulla dolor nulla consequat. Deserunt tempor adipisicing sint ipsum laboris mollit tempor velit culpa adipisicing. Magna laboris pariatur velit non irure laborum et id ut consequat. Duis pariatur irure sit amet voluptate do ad deserunt elit do culpa non nulla. Sit quis laborum quis non sint sunt ipsum adipisicing pariatur veniam eiusmod laboris dolor consequat.\r\n",
        "DueDate": "2014-01-07",
        "IsInvalid": false,
        "CreatedByUserName": "Jewel",
        "LoyaltyUserId": 9090,
        "RenewedDate": "2017-05-16",
        "NewTypeId": 2,
        "NewLoyaltyUserId": 4954,
        "NewRenewedDate": "2016-06-29",
        "NewDueDate": "2016-09-03"
      },
      {
        "InternalId": "5c13db65bc7e83178226e1e6",
        "SNo": 4,
        "CreatedDate": "2014-08-14",
        "SubscriptionNo": "5c13db659e66d07646e8c66b",
        "CustomerName": "Franco Shields",
        "TypeId": 3,
        "Address1": "983 Ridgewood Avenue",
        "Address2": "Nescatunga",
        "Address3": "South Dakota, 2806",
        "City": "Vallonia",
        "State": "Alaska",
        "Country": "Oregon",
        "Pin": "5627A",
        "Email": "francoshields@rameon.com",
        "Mobile": "+1 (842) 439-2946",
        "Phone": "+1 (881) 564-3257",
        "ModifiedDate": "2016-03-01",
        "Comments": "Qui Lorem eiusmod eu commodo anim sit aute sint velit ut ullamco ipsum eiusmod velit. Ea commodo minim esse culpa et pariatur. Ea Lorem magna reprehenderit et est veniam pariatur aute aute. Eu quis velit veniam et. Fugiat nostrud adipisicing nisi officia deserunt voluptate nostrud aliquip. Amet anim aute incididunt ad nisi ullamco esse aliqua.\r\n",
        "DueDate": "2017-11-24",
        "IsInvalid": false,
        "CreatedByUserName": "Vinson",
        "LoyaltyUserId": 6268,
        "RenewedDate": "2017-12-10",
        "NewTypeId": 2,
        "NewLoyaltyUserId": 8877,
        "NewRenewedDate": "2018-02-13",
        "NewDueDate": "2015-04-20"
      },
      {
        "InternalId": "5c13db656cefd595d9a5d521",
        "SNo": 5,
        "CreatedDate": "2014-06-28",
        "SubscriptionNo": "5c13db65893a39304e9c203f",
        "CustomerName": "Oneil Myers",
        "TypeId": 1,
        "Address1": "707 Terrace Place",
        "Address2": "Grill",
        "Address3": "Maine, 4629",
        "City": "Marenisco",
        "State": "Washington",
        "Country": "North Carolina",
        "Pin": "7715A",
        "Email": "oneilmyers@rameon.com",
        "Mobile": "+1 (938) 413-2885",
        "Phone": "+1 (919) 563-3037",
        "ModifiedDate": "2014-09-11",
        "Comments": "Magna aliqua mollit ad reprehenderit laborum occaecat labore et. Nisi sint sunt anim ipsum aliquip proident ipsum enim magna magna proident. Laborum officia non Lorem occaecat exercitation voluptate. Do laboris duis ullamco adipisicing quis adipisicing irure consectetur.\r\n",
        "DueDate": "2015-05-03",
        "IsInvalid": false,
        "CreatedByUserName": "Brenda",
        "LoyaltyUserId": 6343,
        "RenewedDate": "2015-09-07",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 7148,
        "NewRenewedDate": "2017-12-17",
        "NewDueDate": "2014-08-04"
      },
      {
        "InternalId": "5c13db65561d781f8815a7f3",
        "SNo": 6,
        "CreatedDate": "2017-05-27",
        "SubscriptionNo": "5c13db654fd12ffb8f19c3ea",
        "CustomerName": "Sophia Hartman",
        "TypeId": 1,
        "Address1": "419 Mermaid Avenue",
        "Address2": "Blodgett",
        "Address3": "Georgia, 7564",
        "City": "Odessa",
        "State": "Connecticut",
        "Country": "Federated States Of Micronesia",
        "Pin": "5329A",
        "Email": "sophiahartman@rameon.com",
        "Mobile": "+1 (805) 574-2914",
        "Phone": "+1 (804) 485-3145",
        "ModifiedDate": "2015-10-15",
        "Comments": "Sit fugiat enim cupidatat eu sit qui. Consectetur proident est aute anim ut quis aliqua occaecat nulla eu id veniam consequat. Velit qui proident et in non. Labore Lorem duis non aliquip.\r\n",
        "DueDate": "2016-05-12",
        "IsInvalid": true,
        "CreatedByUserName": "Mona",
        "LoyaltyUserId": 9936,
        "RenewedDate": "2015-08-03",
        "NewTypeId": 1,
        "NewLoyaltyUserId": 9261,
        "NewRenewedDate": "2014-05-19",
        "NewDueDate": "2017-02-03"
      },
      {
        "InternalId": "5c13db655b29679d5f6e7c0c",
        "SNo": 7,
        "CreatedDate": "2016-12-18",
        "SubscriptionNo": "5c13db65a26d56dd74fffb13",
        "CustomerName": "Hebert Salas",
        "TypeId": 1,
        "Address1": "447 Elmwood Avenue",
        "Address2": "Lowell",
        "Address3": "Puerto Rico, 2320",
        "City": "Worton",
        "State": "Marshall Islands",
        "Country": "Wyoming",
        "Pin": "2223A",
        "Email": "hebertsalas@rameon.com",
        "Mobile": "+1 (832) 487-3141",
        "Phone": "+1 (965) 420-3980",
        "ModifiedDate": "2016-04-26",
        "Comments": "Ipsum duis officia ullamco do do est ad dolor sit qui reprehenderit ad. Labore dolore aute anim sint. Magna esse laboris consequat ipsum non cupidatat eu consequat mollit proident in. Excepteur et incididunt elit ullamco sunt deserunt enim consectetur consectetur velit fugiat deserunt. Aute nulla et et ea esse eu quis deserunt proident consectetur. Ea eu laborum magna ipsum quis nostrud non. Nisi nulla eu reprehenderit laborum sit enim.\r\n",
        "DueDate": "2014-05-15",
        "IsInvalid": false,
        "CreatedByUserName": "Edwina",
        "LoyaltyUserId": 7515,
        "RenewedDate": "2018-01-27",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 5043,
        "NewRenewedDate": "2017-12-19",
        "NewDueDate": "2017-10-29"
      },
      {
        "InternalId": "5c13db657dd0eb9ccd94b37b",
        "SNo": 8,
        "CreatedDate": "2014-06-21",
        "SubscriptionNo": "5c13db6518f276ccda148a41",
        "CustomerName": "Tran Moon",
        "TypeId": 2,
        "Address1": "454 Barwell Terrace",
        "Address2": "Lawrence",
        "Address3": "American Samoa, 2883",
        "City": "Glidden",
        "State": "Palau",
        "Country": "Maryland",
        "Pin": "1684A",
        "Email": "tranmoon@rameon.com",
        "Mobile": "+1 (882) 412-2905",
        "Phone": "+1 (858) 576-3045",
        "ModifiedDate": "2016-04-22",
        "Comments": "Adipisicing ut ex adipisicing dolore cupidatat non proident irure veniam excepteur mollit. Cillum ullamco dolor consequat laborum est elit eu consequat deserunt reprehenderit occaecat exercitation. Nulla aliqua tempor id voluptate culpa incididunt aliquip in est ea fugiat occaecat. Id excepteur consequat laboris anim incididunt do incididunt aute dolor. Commodo occaecat qui sint cupidatat occaecat est laborum consectetur aute nisi ad Lorem minim. Nulla ullamco amet nulla magna ipsum amet nostrud consequat veniam. Aute nisi exercitation ipsum nulla deserunt velit nulla nisi eu irure veniam.\r\n",
        "DueDate": "2015-11-15",
        "IsInvalid": true,
        "CreatedByUserName": "Gwendolyn",
        "LoyaltyUserId": 9686,
        "RenewedDate": "2014-11-25",
        "NewTypeId": 2,
        "NewLoyaltyUserId": 8954,
        "NewRenewedDate": "2017-10-17",
        "NewDueDate": "2015-08-28"
      },
      {
        "InternalId": "5c13db65f318178e4cac4eff",
        "SNo": 9,
        "CreatedDate": "2015-06-26",
        "SubscriptionNo": "5c13db654952fda9537d9df7",
        "CustomerName": "Mitchell Simpson",
        "TypeId": 2,
        "Address1": "457 Lawrence Avenue",
        "Address2": "Dennard",
        "Address3": "Vermont, 1132",
        "City": "Stockdale",
        "State": "North Dakota",
        "Country": "New Jersey",
        "Pin": "1081A",
        "Email": "mitchellsimpson@rameon.com",
        "Mobile": "+1 (904) 574-2635",
        "Phone": "+1 (928) 499-3869",
        "ModifiedDate": "2015-06-12",
        "Comments": "Aliqua enim excepteur incididunt officia ullamco labore veniam ex dolore. Esse ullamco veniam cillum id mollit nostrud veniam. Est et nulla et culpa.\r\n",
        "DueDate": "2016-01-26",
        "IsInvalid": false,
        "CreatedByUserName": "Wooten",
        "LoyaltyUserId": 7202,
        "RenewedDate": "2018-08-21",
        "NewTypeId": 2,
        "NewLoyaltyUserId": 3798,
        "NewRenewedDate": "2015-09-08",
        "NewDueDate": "2017-05-24"
      },
      {
        "InternalId": "5c13db6564c4e4d844b418ef",
        "SNo": 10,
        "CreatedDate": "2014-04-01",
        "SubscriptionNo": "5c13db654bbefe0cf4e647a4",
        "CustomerName": "Carlene Floyd",
        "TypeId": 1,
        "Address1": "867 Quay Street",
        "Address2": "Faxon",
        "Address3": "Wisconsin, 8163",
        "City": "Esmont",
        "State": "Colorado",
        "Country": "Delaware",
        "Pin": "5673A",
        "Email": "carlenefloyd@rameon.com",
        "Mobile": "+1 (916) 439-3381",
        "Phone": "+1 (984) 507-3543",
        "ModifiedDate": "2015-04-29",
        "Comments": "In fugiat reprehenderit reprehenderit commodo sunt aute occaecat. Do cupidatat id dolore aute enim aliquip ipsum nulla duis occaecat ea id ex excepteur. Fugiat veniam velit id qui est nostrud ad. Nulla culpa pariatur occaecat nostrud dolore ipsum dolor ad do incididunt. Ullamco aliquip ex elit duis reprehenderit adipisicing dolor in aute sit. Consequat ut est occaecat enim nisi id duis magna.\r\n",
        "DueDate": "2015-06-02",
        "IsInvalid": false,
        "CreatedByUserName": "Wade",
        "LoyaltyUserId": 4495,
        "RenewedDate": "2014-06-05",
        "NewTypeId": 1,
        "NewLoyaltyUserId": 7539,
        "NewRenewedDate": "2016-07-11",
        "NewDueDate": "2015-12-13"
      },
      {
        "InternalId": "5c13db657a7ddb63106938cf",
        "SNo": 11,
        "CreatedDate": "2016-12-15",
        "SubscriptionNo": "5c13db651a748d1a2040f9ca",
        "CustomerName": "Suzanne Kent",
        "TypeId": 1,
        "Address1": "813 Lacon Court",
        "Address2": "Boling",
        "Address3": "Massachusetts, 3044",
        "City": "Edinburg",
        "State": "Virgin Islands",
        "Country": "Hawaii",
        "Pin": "9952A",
        "Email": "suzannekent@rameon.com",
        "Mobile": "+1 (899) 491-2046",
        "Phone": "+1 (842) 446-3555",
        "ModifiedDate": "2014-01-17",
        "Comments": "Elit qui duis excepteur occaecat. Sit deserunt enim eiusmod elit. Consequat id ullamco anim nostrud labore commodo fugiat dolore proident dolor consectetur minim. Et in veniam ex ad cillum anim nostrud. Minim mollit amet cupidatat mollit commodo. Deserunt dolore occaecat mollit aliquip exercitation deserunt. Cillum qui anim dolor esse non dolor et proident irure duis enim occaecat.\r\n",
        "DueDate": "2018-08-04",
        "IsInvalid": true,
        "CreatedByUserName": "Nona",
        "LoyaltyUserId": 246,
        "RenewedDate": "2016-06-22",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 3448,
        "NewRenewedDate": "2017-08-14",
        "NewDueDate": "2016-07-05"
      },
      {
        "InternalId": "5c13db65292f5eb030539791",
        "SNo": 12,
        "CreatedDate": "2015-05-24",
        "SubscriptionNo": "5c13db65fc729ee50fd533df",
        "CustomerName": "Marian Blair",
        "TypeId": 3,
        "Address1": "959 Newel Street",
        "Address2": "Broadlands",
        "Address3": "Kentucky, 8697",
        "City": "Kieler",
        "State": "Michigan",
        "Country": "New Mexico",
        "Pin": "8812A",
        "Email": "marianblair@rameon.com",
        "Mobile": "+1 (941) 445-2040",
        "Phone": "+1 (981) 574-3726",
        "ModifiedDate": "2017-01-25",
        "Comments": "Veniam do Lorem esse pariatur proident irure nisi cillum tempor et mollit adipisicing ea nulla. Cillum nulla fugiat pariatur reprehenderit magna tempor aliquip deserunt pariatur pariatur sint sit aliquip minim. Et enim sit esse nulla nisi ullamco do dolor commodo.\r\n",
        "DueDate": "2015-09-10",
        "IsInvalid": false,
        "CreatedByUserName": "Morse",
        "LoyaltyUserId": 4738,
        "RenewedDate": "2016-08-03",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 5393,
        "NewRenewedDate": "2017-07-12",
        "NewDueDate": "2018-08-11"
      },
      {
        "InternalId": "5c13db65d103ad0e58c7c310",
        "SNo": 13,
        "CreatedDate": "2015-07-26",
        "SubscriptionNo": "5c13db65764a5c522a54c2a3",
        "CustomerName": "Mercado Hampton",
        "TypeId": 1,
        "Address1": "600 Waldane Court",
        "Address2": "Derwood",
        "Address3": "Oklahoma, 6814",
        "City": "Maury",
        "State": "Louisiana",
        "Country": "Minnesota",
        "Pin": "1614A",
        "Email": "mercadohampton@rameon.com",
        "Mobile": "+1 (890) 495-3672",
        "Phone": "+1 (970) 539-3051",
        "ModifiedDate": "2014-07-18",
        "Comments": "Ipsum ex qui deserunt enim occaecat cillum enim est do consequat occaecat labore incididunt sint. Ipsum incididunt do et consectetur. Ipsum velit aliqua incididunt nulla. Occaecat nulla incididunt cupidatat anim in non proident excepteur exercitation. Commodo dolore magna cillum duis veniam veniam laboris ullamco in. Magna aliquip deserunt sit nulla labore esse nulla ut culpa nostrud fugiat. Mollit eu sint velit velit.\r\n",
        "DueDate": "2017-03-11",
        "IsInvalid": true,
        "CreatedByUserName": "Amelia",
        "LoyaltyUserId": 883,
        "RenewedDate": "2018-08-01",
        "NewTypeId": 1,
        "NewLoyaltyUserId": 1082,
        "NewRenewedDate": "2018-08-13",
        "NewDueDate": "2018-01-07"
      },
      {
        "InternalId": "5c13db6526aa12d26e2acbde",
        "SNo": 14,
        "CreatedDate": "2015-12-15",
        "SubscriptionNo": "5c13db6562af354d24629b5a",
        "CustomerName": "Crawford Ewing",
        "TypeId": 3,
        "Address1": "788 Metrotech Courtr",
        "Address2": "Kenvil",
        "Address3": "Virginia, 5793",
        "City": "Williams",
        "State": "Northern Mariana Islands",
        "Country": "South Carolina",
        "Pin": "162A",
        "Email": "crawfordewing@rameon.com",
        "Mobile": "+1 (849) 442-2793",
        "Phone": "+1 (884) 575-3040",
        "ModifiedDate": "2014-06-05",
        "Comments": "Esse laboris mollit in ipsum sit consequat eu deserunt consectetur velit magna est fugiat. Commodo ullamco nostrud labore deserunt velit laboris cillum ex magna consequat. Veniam dolore amet eu ullamco. In tempor occaecat sit velit Lorem anim ullamco ad. Amet sint qui voluptate dolor laboris deserunt eu dolore ipsum veniam culpa. Irure proident anim ullamco exercitation.\r\n",
        "DueDate": "2018-06-02",
        "IsInvalid": true,
        "CreatedByUserName": "Vang",
        "LoyaltyUserId": 356,
        "RenewedDate": "2017-10-05",
        "NewTypeId": 1,
        "NewLoyaltyUserId": 5514,
        "NewRenewedDate": "2015-01-10",
        "NewDueDate": "2015-05-25"
      },
      {
        "InternalId": "5c13db65dbcac15884572e0f",
        "SNo": 15,
        "CreatedDate": "2016-02-01",
        "SubscriptionNo": "5c13db658cd2f05535787322",
        "CustomerName": "Traci Owens",
        "TypeId": 1,
        "Address1": "261 Holmes Lane",
        "Address2": "Henrietta",
        "Address3": "Texas, 5100",
        "City": "Belmont",
        "State": "New Hampshire",
        "Country": "District Of Columbia",
        "Pin": "5875A",
        "Email": "traciowens@rameon.com",
        "Mobile": "+1 (872) 524-3257",
        "Phone": "+1 (859) 530-2636",
        "ModifiedDate": "2017-10-12",
        "Comments": "Enim ut nostrud commodo cupidatat sit esse eiusmod ipsum culpa non. Sit proident eiusmod do aute fugiat officia enim magna et ut consectetur. Tempor enim laboris sit id magna ut Lorem pariatur veniam consequat cillum est ex est.\r\n",
        "DueDate": "2018-09-08",
        "IsInvalid": false,
        "CreatedByUserName": "Sharp",
        "LoyaltyUserId": 5949,
        "RenewedDate": "2018-03-04",
        "NewTypeId": 1,
        "NewLoyaltyUserId": 6591,
        "NewRenewedDate": "2018-06-10",
        "NewDueDate": "2016-08-26"
      },
      {
        "InternalId": "5c13db65df57e5f2017ce5a5",
        "SNo": 16,
        "CreatedDate": "2017-11-27",
        "SubscriptionNo": "5c13db654c57a4e13232bbfb",
        "CustomerName": "Kidd Webb",
        "TypeId": 3,
        "Address1": "421 Guider Avenue",
        "Address2": "Chloride",
        "Address3": "Tennessee, 7707",
        "City": "Hiwasse",
        "State": "West Virginia",
        "Country": "Indiana",
        "Pin": "6933A",
        "Email": "kiddwebb@rameon.com",
        "Mobile": "+1 (863) 454-3962",
        "Phone": "+1 (808) 497-3670",
        "ModifiedDate": "2014-11-06",
        "Comments": "Nulla proident sint ut est Lorem est id deserunt enim dolore non id et ut. Non esse consectetur magna irure qui veniam ad officia officia. Magna quis deserunt ea aute fugiat pariatur nisi amet qui. Cillum culpa velit occaecat exercitation reprehenderit cupidatat esse dolor. Exercitation esse qui dolore sit duis aliqua elit nisi fugiat non nulla. Qui proident incididunt minim enim fugiat esse tempor enim do laboris consequat ut.\r\n",
        "DueDate": "2016-12-23",
        "IsInvalid": true,
        "CreatedByUserName": "Inez",
        "LoyaltyUserId": 5782,
        "RenewedDate": "2017-06-04",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 345,
        "NewRenewedDate": "2016-08-12",
        "NewDueDate": "2014-07-14"
      },
      {
        "InternalId": "5c13db6532a212ac72eceb2e",
        "SNo": 17,
        "CreatedDate": "2018-09-11",
        "SubscriptionNo": "5c13db65a58a95a14ca9a093",
        "CustomerName": "Nguyen Rollins",
        "TypeId": 2,
        "Address1": "624 Jardine Place",
        "Address2": "Reno",
        "Address3": "Nevada, 7874",
        "City": "Elizaville",
        "State": "New York",
        "Country": "Alabama",
        "Pin": "3525A",
        "Email": "nguyenrollins@rameon.com",
        "Mobile": "+1 (812) 456-3247",
        "Phone": "+1 (954) 429-3791",
        "ModifiedDate": "2015-12-09",
        "Comments": "Officia eiusmod incididunt do duis irure mollit labore aliquip in tempor esse sunt ut enim. Non ut sint enim consequat ad ad ex quis in ex laboris reprehenderit. Aliquip esse consectetur id ad ut. Nulla incididunt labore ad adipisicing deserunt laborum sunt sint. Cillum voluptate non fugiat in anim commodo eiusmod id qui excepteur veniam deserunt sint et. Proident laboris exercitation cillum veniam elit esse nulla occaecat minim labore nulla elit velit.\r\n",
        "DueDate": "2014-12-29",
        "IsInvalid": false,
        "CreatedByUserName": "Hardy",
        "LoyaltyUserId": 8810,
        "RenewedDate": "2018-12-13",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 1124,
        "NewRenewedDate": "2017-05-29",
        "NewDueDate": "2016-01-06"
      },
      {
        "InternalId": "5c13db65bfc21b51a6c4a30f",
        "SNo": 18,
        "CreatedDate": "2017-03-27",
        "SubscriptionNo": "5c13db65771df6ea26f5a408",
        "CustomerName": "Jodie Foster",
        "TypeId": 1,
        "Address1": "246 Irving Street",
        "Address2": "Coventry",
        "Address3": "Nebraska, 114",
        "City": "Riceville",
        "State": "Pennsylvania",
        "Country": "Florida",
        "Pin": "3145A",
        "Email": "jodiefoster@rameon.com",
        "Mobile": "+1 (892) 401-2568",
        "Phone": "+1 (932) 503-2830",
        "ModifiedDate": "2014-08-30",
        "Comments": "Ipsum veniam exercitation cupidatat laboris enim velit id reprehenderit anim consequat consequat est nostrud. Quis culpa aliquip magna esse ea qui minim excepteur. Velit id ea eiusmod et fugiat. Laboris excepteur irure ex proident enim esse ex aute veniam irure labore.\r\n",
        "DueDate": "2014-07-05",
        "IsInvalid": false,
        "CreatedByUserName": "Marks",
        "LoyaltyUserId": 5118,
        "RenewedDate": "2016-09-28",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 920,
        "NewRenewedDate": "2015-06-03",
        "NewDueDate": "2015-11-02"
      },
      {
        "InternalId": "5c13db65e9855765c475cfdb",
        "SNo": 19,
        "CreatedDate": "2016-05-18",
        "SubscriptionNo": "5c13db658b1c762a15759c65",
        "CustomerName": "Cash Pickett",
        "TypeId": 1,
        "Address1": "557 Fleet Street",
        "Address2": "Blackgum",
        "Address3": "Mississippi, 6314",
        "City": "Woodlands",
        "State": "Montana",
        "Country": "Utah",
        "Pin": "4455A",
        "Email": "cashpickett@rameon.com",
        "Mobile": "+1 (993) 462-2720",
        "Phone": "+1 (817) 546-3510",
        "ModifiedDate": "2014-06-05",
        "Comments": "Magna pariatur dolor proident nulla dolor duis esse commodo. Aute magna do anim ea amet proident ex ipsum esse aliqua pariatur nulla. Officia consectetur aliqua sit ullamco nulla ex. Nostrud do ipsum sit cillum amet ipsum consectetur nulla. Et cupidatat eiusmod minim ullamco aute eiusmod nisi enim proident elit et anim.\r\n",
        "DueDate": "2017-03-10",
        "IsInvalid": false,
        "CreatedByUserName": "Benton",
        "LoyaltyUserId": 3204,
        "RenewedDate": "2017-12-11",
        "NewTypeId": 3,
        "NewLoyaltyUserId": 7870,
        "NewRenewedDate": "2015-04-30",
        "NewDueDate": "2014-12-03"
      },
      {
        "InternalId": "5c13db6598d473473db91b25",
        "SNo": 20,
        "CreatedDate": "2017-12-13",
        "SubscriptionNo": "5c13db652fb9c503cbfbbcfe",
        "CustomerName": "Elizabeth Ingram",
        "TypeId": 1,
        "Address1": "944 Garfield Place",
        "Address2": "Felt",
        "Address3": "Guam, 5167",
        "City": "Hendersonville",
        "State": "Iowa",
        "Country": "Rhode Island",
        "Pin": "7069A",
        "Email": "elizabethingram@rameon.com",
        "Mobile": "+1 (813) 458-3147",
        "Phone": "+1 (820) 425-2428",
        "ModifiedDate": "2016-11-16",
        "Comments": "Mollit fugiat fugiat culpa nisi est exercitation. Ipsum ea et commodo minim eiusmod commodo id incididunt aute labore nostrud occaecat. Culpa ut ipsum ut excepteur eiusmod mollit amet.\r\n",
        "DueDate": "2014-01-02",
        "IsInvalid": false,
        "CreatedByUserName": "Hayes",
        "LoyaltyUserId": 3394,
        "RenewedDate": "2015-08-03",
        "NewTypeId": 2,
        "NewLoyaltyUserId": 9938,
        "NewRenewedDate": "2015-07-06",
        "NewDueDate": "2017-08-07"
      }
    ];

    return data.map(res => {
      const data = res as Subscriber;
      return data;
    });

  }



}
